apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: helterpitanga/appmicro2:5.0
        ports:
        - containerPort: 80
        resources:
         requests:
          memory: 256Mi
          cpu: 250m
         limits:
          memory: 256Mi
          cpu: 250m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general 
---
apiVersion: v1
kind: Service
metadata:
  name: lb-app
spec:
  selector:
    app: app2
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
