apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-gke
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project GKE
  sourceRepos:
  - https://github.com/HelterL/gke-cluster-terraform-github-actions.git
  destinations:
  - namespace: project-gke
    server: https://35.226.126.2            
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"