name: Pipeline GKE com Terraform

on:
  push:
    branches: ["main"]

env:
  GCP_PROJECT_ID: "dark-arcade-390613"

jobs:
  terraform-ci:
    name: "Terraform CI"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./
        shell: bash
    env:
      IMAGE_NAME: helterpitanga/appmicro2:${{ github.workflow_sha }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform validate
        id: validate
        run: terraform validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform plan
        id: plan
        run: terraform plan -out plan.tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform apply
        id: apply
        run: terraform apply plan.tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login para o Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push Docker image
        run: |
          docker build -t $IMAGE_NAME app/.
          docker push $IMAGE_NAME

      - name: Update YAML with new image ID
        run: |
          sed -i 's/image: helterpitanga.*/image: $IMAGE_NAME/g' app/applicationdeploy/appdeploy.yml

        # Setup gcloud CLI
      - name: Setup gcloud CLI
        id: "auth"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}
          location: ${{ vars.LOCATION }}

      - name: Deploy no cluster
        run: |-
          kubectl apply -f app/applicationdeploy/appdeploy.yml
          kubectl get pods
